name = "Drill"
author = "SkywardMC"
version = "xxxxxx.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73b9ee45df6e72abf9e484c8a405df82d229063adb3cfb35d1b736d071ff706d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
