name = "Drill"
author = "SkywardMC"
version = "xxxxxx.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b10c51e4790048885a75fc5e20c7e9c273f6bb2005bdeee502b330701317b2b"

[versions]
minecraft = "1.21.1"
neoforge = "21.4.51-beta"
