name = "Additive"
author = "UltraStorm"
version = "1.18.3+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d3bdb38affee27367243c6ee3b99d0a6852e14637c3c946629b0ff8abeebe1f"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
