name = "Drilled-Additive"
author = "UltraStorm"
version = "1.18.5+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feb55bb634fe1cf5286670fb2e26727a0b581d03090e6b67571ea43d229429da"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
