name = "Additive"
author = "UltraStorm"
version = "1.18.3+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9e7f930016e49805f50770996babb485a9639efb64e9b0450d8662bfb15237f"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
