name = "Additive"
author = "UltraStorm"
version = "1.18.3+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd769efc4ba44155adab0f37d38af059b3a06e8154dd09208a16c1c94c4a21a2"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
