name = "Drilled-Additive"
author = "UltraStorm"
version = "1.18.5+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df7459f8d35809bf2e1362409710e9beb070d17e430db932c33d87f652fe977a"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
