name = "Drilled-Additive"
author = "UltraStorm"
version = "1.20.0+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "975bad815ed90791c3f3afa7ed076ecef5a3b69aaed05fe5f057cd07ee436af5"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
