name = "Drill"
author = "UltraStorm + MenacingPerson"
version = "0.1.0-1.20.0+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53da9530a5469b367b2e09867e5296dfd2dbd7c68938b1eef5f32f58cdc3792d"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
