name = "Drilled-Additive"
author = "UltraStorm"
version = "1.20.0+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe3f0672b84799688fd038d889f34085e85cd388959d3896ba0cfa0292439cbb"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
