name = "Drill"
author = "UltraStorm + MenacingPerson"
version = "0.2.1-1.22.0+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2c45ff5ae157c922ddcb61f419503a7012ff495e5cf5d8a4f94f379ca6171bc"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
