name = "Drill"
author = "UltraStorm + MenacingPerson"
version = "1.20.0.0+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25289b0020cd13ef1fc9a12dbc7134dfa5d07360f813712840c05e7fe072b01b"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
