name = "Drill"
author = "UltraStorm + MenacingPerson"
version = "0.1.2-1.21.0+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8fd7f94f019ab55b69aa547f711964afdef23f1a72fb973f8dbea2a44cdec66"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
