name = "Drill"
author = "UltraStorm + MenacingPerson"
version = "0.2.0-1.21.1+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d3684429a10d6724ed7a028ad9e1a5289db6fbfb0b2a17cc746ba0dff35f6d3"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
