name = "Drill"
author = "UltraStorm + MenacingPerson"
version = "0.1.3-1.21.0+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1c13b9cb4e19f759a9864e3e0120be72a25e71b9cee54e0ffc48c536d8f87cd"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
