name = "Drill"
author = "UltraStorm + MenacingPerson"
version = "0.1.2-1.21.0+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dece90faa5cd5c31ee7127e5f2ecc04db3ca04d82ee3b072bd8bf79eea9f5834"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
